version: '2'

services:
    node:
        build:
            context: ./
            dockerfile: ./Dockerfile
        image: wmde/wikit
        volumes:
            - '~/.npm:/.npm'
            - './:/app'
        working_dir: /app
    storybook-docs:
        extends:
            service: node
        ports:
            - '${DOCS_STORYBOOK_PORT}:${DOCS_STORYBOOK_PORT}'
        command: 'lerna run storybook --stream --scope @wmde/wikit-docs -- -- -p ${DOCS_STORYBOOK_PORT} --ci'
    storybook-vue:
        extends:
            service: node
        ports:
            - '${VUECOMPONENTS_STORYBOOK_PORT}:${VUECOMPONENTS_STORYBOOK_PORT}'
        command: 'lerna run storybook --stream --scope @wmde/wikit-vue-components -- -- -p ${VUECOMPONENTS_STORYBOOK_PORT} --ci'
