version: '2'

services:
    node:
        build:
            context: ./
            dockerfile: ./Dockerfile
        image: wmde/wikit
        volumes:
            - '~/.npm:/.npm'
            - './:/app'
        working_dir: /app
    storybook:
        extends:
            service: node
        ports:
            - '${STORYBOOK_PORT}:${STORYBOOK_PORT}'
        command: 'npm run storybook -- -- -- -p ${STORYBOOK_PORT} --ci'
