version: '2'

services:
    node:
        build:
            context: ./
            dockerfile: ./Dockerfile
        image: wmde/wikit
        volumes:
            - '~/.npm:/.npm'
            - '~/.gitconfig:/etc/gitconfig'
            - './:/app'
        working_dir: /app

    storybook:
        extends:
            service: node
        ports:
            - '${STORYBOOK_PORT}:${STORYBOOK_PORT}'
        command: 'npm run --prefix packages/vue-components storybook -- -p ${STORYBOOK_PORT} --ci'
