version: '2'

services:
    node:
        build:
            context: ./
            dockerfile: ./Dockerfile
        image: wmde/wikit
        volumes:
            - '~/.npm:/.npm'
            - '~/.gitconfig:/etc/gitconfig'
            - './:/app'
        working_dir: /app
