on:
  release:
      types:
      - released

name: Verify and Publish tokens and vue-components
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'
      - name: Install
        run: npm ci
      - name: Test
        run: npm run test
      - name: Publish
        run: |
          printf '//registry.npmjs.org/:_authToken=%s\n' '${{ secrets.NPM_AUTH_TOKEN }}' > ~/.npmrc
          npm run publish-tokens-vue
