# This workflow will do
# - a clean install of node dependencies
# - run tests
# - build and upload the storybook to a staging area
#
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

on: push
name: Test and Deploy
jobs:

  changes:
    runs-on: ubuntu-latest
    outputs:
      visual: ${{ steps.filter.outputs.visual }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # chromatic needs access to the history
    - name: Check Paths
      uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          visual:
            - 'tokens/**'
            - 'vue-components/**'

  install:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # chromatic needs access to the history
    - name: Set up node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Cache dependencies
      uses: actions/cache@v2
      id: cache
      with:
        path: |
          node_modules
          */node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
    - name: Install
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci

  test:
    runs-on: ubuntu-latest
    needs: install
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # chromatic needs access to the history
    - name: Set up node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Restore cache
      uses: actions/cache@v2
      with:
        path: |
          node_modules
          */node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
    - name: Test
      run: npm run test

  deploy:
    runs-on: ubuntu-latest
    needs: [changes, install]
    if: ${{ needs.changes.outputs.visual == 'true' }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # chromatic needs access to the history
    - name: Set up node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Restore cache
      uses: actions/cache@v2
      with:
        path: |
          node_modules
          */node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
    - name: Build Storybooks
      run: npm run build:storybook
    - name: Deploy Storybook
      run: npm run chromatic

  browser-tests:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # chromatic needs access to the history
    - name: Set up node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Restore cache
      uses: actions/cache@v2
      with:
        path: |
          node_modules
          */node_modules
    - name: Extract commit hash
      shell: bash
      run: echo "##[set-output name=commit;]$(git rev-parse --short ${GITHUB_SHA})"
      id: extract_commit
    - name: Run e2e cross browser tests
      env:
        SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
        SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
        COMMIT_HASH: ${{ steps.extract_commit.outputs.commit }}
      run: npm run test:e2e
